#!/bin/bash
OPTION=$(whiptail --title "Network card selection" --menu "Please select a network card." 15 60 4 \
"1"  "ens2  MAC: 6CFE54AB65C8"  \
"2"  "enx00e04c680b5d  MAC: 00E04C680B5D"  \
3>&1 1>&2 2>&3)
exitstatus=$?
if [ ${exitstatus} = 0 ]; then
echo "$OPTION"
else
echo "You chose Cancel."
fi
